// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: check_in_queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO check_ins (habit_id, check_in_date)
VALUES ($1, $2)
RETURNING id, habit_id, check_in_date, created_at
`

type CreateCheckInParams struct {
	HabitID     pgtype.UUID
	CheckInDate pgtype.Date
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, createCheckIn, arg.HabitID, arg.CheckInDate)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.CheckInDate,
		&i.CreatedAt,
	)
	return i, err
}
