// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CheckIn, error)
	CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHabit(ctx context.Context, arg DeleteHabitParams) error
	GetHabitByID(ctx context.Context, arg GetHabitByIDParams) (Habit, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListHabitsByUserID(ctx context.Context, userID pgtype.UUID) ([]Habit, error)
	UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error)
}

var _ Querier = (*Queries)(nil)
